[project]
name = "worldmodel"
version = "0.1.0"
description = "World Model Simulation System"
requires-python = ">=3.11"

[tool.pytest.ini_options]
addopts = "--cov=worldmodel/src --cov-report=term --cov-report=xml"
pythonpath = ["worldmodel/src"] 